apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-kv
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      tenantId: "5611623b-9128-461e-9d7f-a0d9c270ead2"
      vaultUrl: "https://zmoog-homelab-kv.vault.azure.net/"
      authSecretRef:
        clientId:
          name: azure-sp-secret
          namespace: external-secrets
          key: client-id
        clientSecret:
          name: azure-sp-secret
          key: client-secret
