image:
  repository: ghcr.io/zmoog/ifq-job
  tag: sha-23cef62
  pullPolicy: IfNotPresent

# Keep default daily schedule for now.
schedule: "0 5 * * *"

otel:
  enabled: false
  # Example collector endpoint:
  # endpoint: http://otel-collector.default.svc.cluster.local:4318/v1/traces
  exporter:
    endpoint: ""
    headers: ""
