image:
  repository: ghcr.io/zmoog/ifq-job
  tag: sha-be1b3db
  pullPolicy: IfNotPresent

schedule: "0 5 * * *"

otel:
  enabled: true
  resourceAttributes: deployment.environment=homelab-kind
  exporter:
    endpoint: http://otel-collector-gateway.observability.svc.cluster.local:4318/v1/traces
    headers: ""
