apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-store-homelab-kind
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zmoog/ops.git
    targetRevision: main
    path: infrastructure/secret-store
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
