apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name | quote }}
spec:
  type: {{ .Values.service.type | quote }}
  selector:
    app.kubernetes.io/name: {{ .Values.name | quote }}
  ports:
    - name: otlp-grpc
      protocol: TCP
      port: {{ .Values.service.otlpGrpcPort }}
      targetPort: otlp-grpc
    - name: otlp-http
      protocol: TCP
      port: {{ .Values.service.otlpHttpPort }}
      targetPort: otlp-http
    - name: prom-metrics
      protocol: TCP
      port: {{ .Values.service.prometheusPort }}
      targetPort: prom-metrics
