apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-kind-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zmoog/ops.git
    targetRevision: main
    path: clusters/homelab-kind/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
