{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secretName }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name }}
    kind: {{ .Values.externalSecret.secretStore.kind }}
  target:
    name: {{ .Values.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: IFQ_USERNAME
      remoteRef:
        key: ifq-username
    - secretKey: IFQ_PASSWORD
      remoteRef:
        key: ifq-password
    - secretKey: DROPBOX_ACCESS_TOKEN
      remoteRef:
        key: dropbox-access-token
    - secretKey: DROPBOX_ROOT_FOLDER
      remoteRef:
        key: dropbox-root-folder
{{- end }}
