apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name | quote }}
data:
  collector.yaml: |
    extensions:
      health_check:
        endpoint: 0.0.0.0:{{ .Values.service.healthPort }}
      pprof:
        endpoint: 0.0.0.0:{{ .Values.service.pprofPort }}
      zpages:
        endpoint: 0.0.0.0:{{ .Values.service.zpagesPort }}
{{- if .Values.discord.enabled }}
      discord:
        bot_token: ${env:{{ .Values.discord.botTokenEnvVar }}}
{{- end }}

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:{{ .Values.service.otlpGrpcPort }}
          http:
            endpoint: 0.0.0.0:{{ .Values.service.otlpHttpPort }}
{{- if .Values.discord.enabled }}
      discord:
        guild_ids: {{ .Values.discord.guildIds | toJson }}
        channel_ids: {{ .Values.discord.channelIds | toJson }}
{{- end }}

    processors:
      memory_limiter:
        check_interval: {{ .Values.collector.memoryLimiter.checkInterval }}
        limit_mib: {{ .Values.collector.memoryLimiter.limitMiB }}
        spike_limit_mib: {{ .Values.collector.memoryLimiter.spikeLimitMiB }}
      batch:
        timeout: {{ .Values.collector.batch.timeout }}

    exporters:
      debug:
        verbosity: {{ .Values.collector.debugExporter.verbosity }}

    service:
      extensions: [health_check, pprof, zpages{{- if .Values.discord.enabled }}, discord{{- end }}]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
        logs:
          receivers: [otlp{{- if .Values.discord.enabled }}, discord{{- end }}]
          processors: [memory_limiter, batch]
          exporters: [debug]
      telemetry:
        metrics:
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: {{ .Values.collector.telemetry.prometheus.host }}
                    port: {{ .Values.collector.telemetry.prometheus.port }}
