apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.name | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name | quote }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ .Values.name | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/component: otel-collector
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    spec:
      containers:
        - name: looter
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          args: ["--config=/conf/collector.yaml"]
          ports:
            - name: otlp-grpc
              containerPort: {{ .Values.service.otlpGrpcPort }}
            - name: otlp-http
              containerPort: {{ .Values.service.otlpHttpPort }}
            - name: health
              containerPort: {{ .Values.service.healthPort }}
            - name: pprof
              containerPort: {{ .Values.service.pprofPort }}
            - name: zpages
              containerPort: {{ .Values.service.zpagesPort }}
          volumeMounts:
            - name: config
              mountPath: /conf
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: health
          readinessProbe:
            httpGet:
              path: /
              port: health
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ .Values.name | quote }}
