{{- if and .Values.discord.enabled .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secretName | quote }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name | quote }}
    kind: {{ .Values.externalSecret.secretStore.kind | quote }}
  target:
    name: {{ .Values.secretName | quote }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.discord.secretKey | quote }}
      remoteRef:
        key: {{ .Values.externalSecret.remoteRefs.discordBotToken | quote }}
{{- end }}
