apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector-gateway-kind
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:zmoog/ops.git
    targetRevision: main
    path: apps/otel-collector/chart
    helm:
      valueFiles:
        - values-kind.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
