image:
  registry: ghcr.io/zmoog/collector
  tag: latest@sha256:6494f21ecaa87d14ae462a188c4215a6ab9ab5ec224dc4776f06ac7e7268dec3

secretName: home-telemetry-collector-secrets

telemetry:
  log:
    level: info

shellycloud:
  collection_interval: "5m"

zcsazzurro:
  things:
    - name: p0
      clientIdEnvVar: ZCS_P0_CLIENT_ID
      authKeyEnvVar: ZCS_P0_AUTH_KEY
      thingKeyEnvVar: ZCS_P0_THING_KEY
    - name: p2
      clientIdEnvVar: ZCS_P2_CLIENT_ID
      authKeyEnvVar: ZCS_P2_AUTH_KEY
      thingKeyEnvVar: ZCS_P2_THING_KEY
