image:
  registry: ghcr.io/zmoog/collector
  tag: latest@sha-bc1f880

secretName: home-telemetry-collector-secrets

telemetry:
  log:
    level: info

shellycloud:
  collection_interval: "1m"

zcsazzurro:
  things:
    - name: p0
      clientIdEnvVar: ZCS_P0_CLIENT_ID
      authKeyEnvVar: ZCS_P0_AUTH_KEY
      thingKeyEnvVar: ZCS_P0_THING_KEY
    - name: p2
      clientIdEnvVar: ZCS_P2_CLIENT_ID
      authKeyEnvVar: ZCS_P2_AUTH_KEY
      thingKeyEnvVar: ZCS_P2_THING_KEY
