apiVersion: v1
kind: Secret
metadata:
  name: home-telemetry-collector-secrets
type: Opaque
stringData:
  ELASTICSEARCH_ENDPOINTS: "https://your-elasticsearch-endpoint"
  ELASTICSEARCH_API_KEY: "your-elasticsearch-api-key"

  WAVINSENTIO_USERNAME: "your-wavinsentio-username"
  WAVINSENTIO_PASSWORD: "your-wavinsentio-password"

  SHELLY_SERVER_URL: "https://shelly-68-eu.shelly.cloud"
  SHELLY_AUTH_KEY: "your-shelly-auth-key"

  TOGGL_API_TOKEN: "your-toggl-api-token"

  ZCS_P0_CLIENT_ID: ""
  ZCS_P0_AUTH_KEY: ""
  ZCS_P0_THING_KEY: ""

  ZCS_P2_CLIENT_ID: ""
  ZCS_P2_AUTH_KEY: ""
  ZCS_P2_THING_KEY: ""
