apiVersion: v1
kind: Secret
metadata:
  name: ifq-job-secrets
type: Opaque
stringData:
  IFQ_USERNAME: "your-ifq-username"
  IFQ_PASSWORD: "your-ifq-password"
  DROPBOX_ACCESS_TOKEN: "your-dropbox-access-token"
  DROPBOX_ROOT_FOLDER: "/Il Fatto Quotidiano"
